version: '3'

services:
  nodejs:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - db:./slow-calculator-database

volumes:
  db:
    external: true

networks:
  default:
    external:
      name: serverdata_slow-calculator
