version: '3'

services:
  nodejs:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./slow-calculator-database:/usr/slow-calculator-backend/slow-calculator-database

networks:
  default:
    external:
      name: serverdata_slow-calculator
